site_name: Python Mini Projeler
site_url: https://ozcanyarimdunya.github.io
site_author: Özcan Yarımdünya
site_description: Python Mini Projeler
copyright: Copyright &copy; 2022 <a href="https://yarimdunya.com" target="_blank">Özcan Yarımdünya<a/>
repo_name: python mini projeler
repo_url: https://github.com/ozcanyarimdunya/python_mini_projeler

markdown_extensions:
  toc:
    permalink: "#"

plugins:
  - search

theme:
  name: material
  custom_dir: theme
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Light mode
  favicon: assets/images/favicon.ico
  icon:
    logo: svg/favicon
  features:
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

extra:
  social:
    - icon: material/web
      link: https://yarimdunya.com
      name: Website
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ozcanyarimdunya
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ozcanyarimdunya
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/ozcanyarimdunya
      name: Github
    - icon: material/gmail
      link: mailto:ozcanyd@gmail.com
      name: Mail
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/3117592/ozcanyarimdunya
      name: Stack Overflow

nav:
  - Anasayfa: index.md
  - Mini Eğitim Seti:
      - Hello World: '01-getting-started/hello-world.md'
